version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379 
    depends_on:
      - db
      - redis
volumes:
  dbdata: