kind: Service
apiVersion: v1
metadata:
  name: k8-rails-service
spec:
  selector:
    app: k8-rails
  type: NodePort
  #type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000