apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-rails-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-rails
  template:
    metadata:
      labels:
        app: k8-rails
    spec:
      containers:
      - name: k8-rails
        image: your_name/newimage:new
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: your_name-secrets
                key: database-url
          - name: SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: your_name-secrets
                key: secret-key-base
        envFrom:
          - secretRef:
              name: name 
